version: 2
references:
  ## Workspaces
  workspace: &workspace
    ~/popmovie

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Indonesia"
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx3g -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError" -Dfile.encoding=utf-8 -Dkotlin.compiler.execution.strategy="in-proces"'

  android_config: &android_config_release
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Indonesia"
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx3g -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=4"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError" -Dfile.encoding=utf-8 -Dkotlin.compiler.execution.strategy="in-proces"'

  remove_properties: &remove_properties
    run:
      name: Removing gradle.properties
      command: rm -rf gradle.properties || true

  install_properties: &install_properties
    run:
      name: Setup environment
      command: bash ./misc/circleci_env_setup.sh

  accept_license: &accept_license
    run:
      name: Accepting License
      command: cp -r licenses/. $ANDROID_HOME/licenses

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

  download_dependencies: &download_dependencies
    run:
      name: Download Dependencies
      command: ./gradlew androidDependencies --no-daemon

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: v1-dependencies-{{ checksum "build.gradle" }}
      paths:
        - ~/.gradle
        - ~/.m2

  share_workflow: &share_workflow
    run:
      name: Put data to share in workflow
      command: |
        mkdir ~/popmovie/shared
        echo $CIRCLE_BUILD_NUM > shared/build_number
        echo $CIRCLE_BUILD_URL > shared/build_url
        git log -1 --pretty=format:"*%h* (%an): %s" > shared/build_title

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: shared
      paths:
        - build_number
        - build_url
        - build_title

  store_artifacts: &store_artifacts
    store_artifacts:
      path: app/build/outputs/apk/
      destination: apks/

  store_report: &store_report
    store_artifacts:
      path: build_reports/
      destination: build_reports/

  ## Keys
#  decode_android_key: &decode_android_key
#    run:
#      name: Decode Android key store
#      command: echo $KEYSTORE | base64 -di | tee keystore.jks app/keystore.jks >/dev/null
#
#  create_google_play_key: &create_google_play_key
#    run:
#      name: Create Google Play key
#      command: echo $GOOGLE_PLAY_KEY > google-play-key.json

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
#      - *accept_license
      - *remove_properties
      - *install_properties
      - *restore_gradle_cache
      - *download_dependencies
      - *save_gradle_cache
      - run:
          name: Assemble Debug
          command: |
            echo "Building WITH proguard. PR"
            ./gradlew clean assembleDevDebug -PuseProguard=true -PbuildNumber=$CIRCLE_BUILD_NUM --parallel --max-workers=2 --no-daemon -PdisablePreDex --no-build-cache --stacktrace
      - run:
          name: Test Debug
          command: |
            echo "Running Development Tests"
            ./gradlew testDevDebugUUnitTest -PbuildNumber=$CIRCLE_BUILD_NUM --parallel --max-workers=2 --no-daemon -PdisablePreDex --build-cache --stacktrace
      - run:
          name: Apk info
          command: |
            apk=$(find ~/popmovie/app/build/outputs/apk/ -name '*.apk' -print -quit)
            echo $apk
            apkanalyzer dex references $apk

  build_development:
    <<: *android_config
    steps:
      - checkout
#      - *accept_license
      - *remove_properties
      - *install_properties
      - *restore_gradle_cache
      - *download_dependencies
      - *save_gradle_cache
      - run:
          name: Assemble Debug
          command: |
            echo "Building WITH proguard. PR"
            ./gradlew clean assembleDevDebug -PuseProguard=true -PbuildNumber=$CIRCLE_BUILD_NUM --parallel --max-workers=2 --no-daemon -PdisablePreDex --no-build-cache --stacktrace
      - run:
          name: Test Debug
          command: |
            echo "Running Development Tests"
            ./gradlew testDevDebugUUnitTest -PbuildNumber=$CIRCLE_BUILD_NUM --parallel --max-workers=2 --no-daemon -PdisablePreDex --build-cache --stacktrace
      - run:
          name: Apk info
          command: |
            apk=$(find ~/popmovie/app/build/outputs/apk/ -name '*.apk' -print -quit)
            echo $apk
            apkanalyzer dex references $apk
      - run:
          name: Release notes
          command: |
            mkdir -p development
            touch development/release_notes.txt
            echo "Debug build for regression testing `date '+%Y-%m-%d'`" >> development/release_notes.txt
            git log `git describe --tags --abbrev=0 HEAD^`..HEAD --pretty=format:"%s // %an" >> development/release_notes.txt
      - *share_workflow
      - *persist_to_workspace
      - *store_artifacts
      - *store_report
      - deploy:
          name: "Deploy to Development build to Fabric"
          command: |
            echo "Branch: ${CIRCLE_BRANCH} , PR: ${CIRCLE_PULL_REQUEST}"
            ./gradlew crashlyticsUploadDistributionDevDebug --stacktrace --debug --no-daemon

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - develop
                - staging
                - alpha
                - release
                - /^staging/.*/
                - /^alpha/.*/
                - /^release/.*/

  development:
    jobs:
      - build_development:
          filters:
            branches:
              only:
                - develop
